// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: services/user-service/proto/register.proto

package E_Commerce

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRegister) Reset() {
	*x = ReqRegister{}
	mi := &file_services_user_service_proto_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegister) ProtoMessage() {}

func (x *ReqRegister) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegister.ProtoReflect.Descriptor instead.
func (*ReqRegister) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_register_proto_rawDescGZIP(), []int{0}
}

func (x *ReqRegister) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqRegister) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReqRegister) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResRegister) Reset() {
	*x = ResRegister{}
	mi := &file_services_user_service_proto_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResRegister) ProtoMessage() {}

func (x *ResRegister) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_service_proto_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResRegister.ProtoReflect.Descriptor instead.
func (*ResRegister) Descriptor() ([]byte, []int) {
	return file_services_user_service_proto_register_proto_rawDescGZIP(), []int{1}
}

func (x *ResRegister) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_services_user_service_proto_register_proto protoreflect.FileDescriptor

var file_services_user_service_proto_register_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x27, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x4b, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x15, 0x2e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x5a, 0x79, 0x70, 0x72, 0x75, 0x73, 0x68, 0x31, 0x38, 0x2f, 0x45, 0x2d, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x72, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_services_user_service_proto_register_proto_rawDescOnce sync.Once
	file_services_user_service_proto_register_proto_rawDescData []byte
)

func file_services_user_service_proto_register_proto_rawDescGZIP() []byte {
	file_services_user_service_proto_register_proto_rawDescOnce.Do(func() {
		file_services_user_service_proto_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_user_service_proto_register_proto_rawDesc), len(file_services_user_service_proto_register_proto_rawDesc)))
	})
	return file_services_user_service_proto_register_proto_rawDescData
}

var file_services_user_service_proto_register_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_user_service_proto_register_proto_goTypes = []any{
	(*ReqRegister)(nil), // 0: register.ReqRegister
	(*ResRegister)(nil), // 1: register.ResRegister
}
var file_services_user_service_proto_register_proto_depIdxs = []int32{
	0, // 0: register.RegisterService.Register:input_type -> register.ReqRegister
	1, // 1: register.RegisterService.Register:output_type -> register.ResRegister
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_user_service_proto_register_proto_init() }
func file_services_user_service_proto_register_proto_init() {
	if File_services_user_service_proto_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_user_service_proto_register_proto_rawDesc), len(file_services_user_service_proto_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_user_service_proto_register_proto_goTypes,
		DependencyIndexes: file_services_user_service_proto_register_proto_depIdxs,
		MessageInfos:      file_services_user_service_proto_register_proto_msgTypes,
	}.Build()
	File_services_user_service_proto_register_proto = out.File
	file_services_user_service_proto_register_proto_goTypes = nil
	file_services_user_service_proto_register_proto_depIdxs = nil
}
